version: '3.1'

services:

  php-fpm:
    build: ./api/docker/php
    volumes:
      - ./api:/app
      - ./api/docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /app
    container_name: 'php-fpm'
    environment:
      PHP_IDE_CONFIG: serverName=docker
    restart: always

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    depends_on:
      - php-fpm
    ports:
      - '8080:80'
    volumes:
      - ./api:/app
      - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mysql:
    image: mysql
    container_name: 'mysql'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./api/docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new-emartportal
    ports:
      - '3306:3306'


  npm:
    image: node:alpine
    working_dir: /app
    volumes:
        - ./front:/app
    entrypoint: /bin/sh
    ports:
        - '8000:8000'
    tty: true
